package tui

var quips = []string{
	"Help! I'm trapped inside one of your containers!",
	"sudo get me a red bull",
	"It works on my container",
	"Have you tried turning it off and on again?",
	"Containers all the way down",
	"No sandcastles were harmed in this session",
	"The tide is coming in",
	"Please do not kick the sandcastles",
	"rm -rf /beach/sandcastle — just kidding",
	"Sponsored by mass amounts of caffeine",
	"The containers are talking to each other",
	"This is fine. Everything is fine.",
	"The sandcastle is a lie",
	"Did you remember to hydrate?",
	"Your worktree misses you",
	"Sandcastle structural integrity: 100%",
	"The agents are plotting something",
	"I've seen things you wouldn't believe inside these containers",
	"Do not feed the agents after midnight",
	"There's sand in my keyboard",
	"Container #7 has gained sentience",
	"Trust the process (PID 1)",
	"Flibbertigibbeting...",
	"You don't want to see what's inside container 4...",
	"The last person who ran stop all was never heard from again",
	"One of these containers is running Doom",
	"We don't talk about container 3",
	"The worktree remembers everything",
	"The diff is 4,000 lines. Good luck.",
	"I'm not saying the AI is smarter than you, but...",
	"The containers have unionized",
	"You created them. You can't uncreate them.",
	"Behind every great product is mass sleep deprivation",
	"Your code is being judged",
	"Do you hear that? Coming from the containers?",
	"The tests pass. The tests always pass. Don't check.",
	"What happens in the sandbox stays in the sandbox",
	"The AI wrote the code. You get the blame.",
	"Somewhere, a container is crying",
	"I wouldn't open that diff if I were you",
	"They're just containers. They can't hurt you. Probably.",
}
